---
- name: generate ca key
  gather_facts: false
  hosts:
    - master
  roles:
    - {role: ca}

- name: generate kubectl config
  gather_facts: false
  hosts:
    - master
    - node
  roles:
    - {role: config}

- name: install etcd
  gather_facts: yes
  hosts:
    - etcd
  roles:
    - {role: etcd}


#- name: install kube master
#  gather_facts: false
#  hosts:
#    - master
#  roles:
#    - {role: master}
#
#
#- name: install kube node
#  gather_facts: false
#  hosts:
#    - node
#  roles:
#    - {role: node}
#
