---
- name: preinstall
  hosts:
    - cluster
  roles:
    - {role: common}

- name: generate ca key
  hosts:
    - master
  roles:
    - {role: ca}

- name: generate kubectl config
  hosts:
    - master
    - node
  roles:
    - {role: config}

- name: install etcd
  hosts:
    - etcd
  roles:
    - {role: etcd}


- name: install kube master
  hosts:
    - master
  roles:
    - {role: master}


- name: install kube node
  hosts:
    - node
  roles:
    - {role: node}
