---
- name: make sure kubedns directory exists
  file:
    path: "{{ KUBE_DIR }}/kubedns"
    state: directory
    
- name: copy kubedns yaml  to master machine
  template:
    src: "{{ item }}.j2"
    dest: "{{ KUBE_DIR }}/kubedns/{{ item }}"
  with_items:
    - "kubedns.yaml"

- name: install kubedns
  shell: kubectl create -f kubedns.yaml
  args:
    chdir: "{{ KUBE_DIR }}/kubedns"
