---
- name: make sure efk directory exists
  file:
    path: "{{ KUBE_DIR }}/efk"
    state: directory
    
- name: copy efk yaml to master machine
  template:
    src: "{{ item }}.j2"
    dest: "{{ KUBE_DIR }}/efk/{{ item }}"
  with_items:
    - "elasticsearch.yaml"
    - "fluentd.yaml"
    - "kibana.yaml"

- name: install elasticsearch
  shell: kubectl create -f elasticsearch.yaml
  args:
    chdir: "{{ KUBE_DIR }}/efk"

- name: install fluentd
  shell: kubectl create -f fluentd.yaml
  args:
    chdir: "{{ KUBE_DIR }}/efk"

- name: install kibana
  shell: kubectl create -f kibana.yaml
  args:
    chdir: "{{ KUBE_DIR }}/efk"
