---
- name: disable setenforce
  selinux:
    state: disabled
  ignore_errors: True
  run_once: True

- name: setenforce 0
  shell: setenforce 0
  ignore_errors: True
  run_once: True

- name: shutdown firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: True
  run_once: True

- name: install epel-release
  yum:
    name: "epel-release"
    state: latest
  run_once: True

- name: install pip
  yum:
    name: "python-pip"
    state: latest
  run_once: True

- name: pip install  docker-py
  pip:
    name: "docker-py"
    state: latest
  run_once: True
